language: generic

services:
  - docker

before_install:
  -  docker pull hadolint/hadolint

script:
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < slim/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 - < alpine/Dockerfile
